import { useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Check, Copy, BarChart3, Download } from 'lucide-react';

// ─── Stage pipeline for progress indicator ────────────────────────────────────

const STAGES = [
  { key: 'analyzing',  label: 'Analyzing business context', icon: '🔍' },
  { key: 'market',     label: 'Market intelligence',        icon: '📊' },
  { key: 'finance',    label: 'Financial planning',         icon: '💰' },
  { key: 'schemes',    label: 'Government schemes',         icon: '🏛️' },
  { key: 'brand',      label: 'Brand strategy',             icon: '✨' },
  { key: 'marketing',  label: 'Marketing plan',             icon: '📣' },
  { key: 'aggregating',label: 'Compiling report',           icon: '📋' },
];

interface ReportProgressProps {
  currentStage: string;
  message: string;
}

export function ReportProgress({ currentStage, message }: ReportProgressProps) {
  const currentIdx = STAGES.findIndex(s => s.key === currentStage);

  return (
    <div className="w-full max-w-xl py-3">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-3.5 h-3.5 border-2 border-primary border-t-transparent rounded-full animate-spin flex-shrink-0" />
        <p className="text-sm text-primary font-medium">{message || 'Building your report…'}</p>
      </div>
      <div className="space-y-1.5">
        {STAGES.map((stage, i) => {
          const isDone   = i < currentIdx;
          const isActive = i === currentIdx;
          return (
            <div
              key={stage.key}
              className={`flex items-center gap-3 px-3 py-2 rounded-lg transition-all duration-300 ${
                isActive ? 'bg-primary/10 border border-primary/20' :
                isDone   ? 'opacity-50' : 'opacity-20'
              }`}
            >
              <span className="text-sm">{stage.icon}</span>
              <span className={`text-[13px] flex-1 ${isActive ? 'text-white' : 'text-white/60'}`}>
                {stage.label}
              </span>
              {isDone   && <span className="text-primary text-xs">✓</span>}
              {isActive && <div className="w-3 h-3 border border-primary border-t-transparent rounded-full animate-spin" />}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ─── PDF export via hidden iframe print ───────────────────────────────────────

function printReportAsPDF(bodyEl: HTMLElement, title: string) {
  const iframe = document.createElement('iframe');
  iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:0;height:0;border:0;';
  document.body.appendChild(iframe);

  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!doc) { document.body.removeChild(iframe); return; }

  doc.open();
  doc.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    @page { margin: 32px 40px; }
    body { font-family: Georgia, 'Times New Roman', serif; color: #111; font-size: 13px; line-height: 1.7; max-width: 720px; margin: 0 auto; }
    h1 { font-size: 22px; margin: 0 0 4px; }
    h2 { font-size: 17px; margin-top: 28px; padding-bottom: 6px; border-bottom: 1px solid #ddd; }
    h3 { font-size: 14px; margin-top: 16px; }
    p  { margin: 8px 0; }
    ul, ol { padding-left: 20px; margin: 6px 0; }
    li { margin: 3px 0; }
    strong { font-weight: 700; }
    table { width: 100%; border-collapse: collapse; margin: 14px 0; font-size: 12px; page-break-inside: avoid; }
    th { background: #f4f4f4; font-weight: 600; padding: 7px 10px; border: 1px solid #ccc; text-align: left; }
    td { padding: 6px 10px; border: 1px solid #ddd; }
    tr:nth-child(even) td { background: #fafafa; }
    blockquote { border-left: 3px solid #04a16d; padding: 6px 14px; margin: 14px 0; color: #444; background: #f9f9f9; }
    hr { border: none; border-top: 1px solid #eee; margin: 18px 0; }
    a { color: #04a16d; }
    code { background: #f4f4f4; padding: 1px 5px; border-radius: 3px; font-size: 11px; font-family: monospace; }
    .pdf-footer { margin-top: 36px; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 12px; }
  </style>
</head>
<body>
${bodyEl.innerHTML}
<div class="pdf-footer">Generated by MAYA — AI Business Assistant for Indian MSMEs</div>
</body>
</html>`);
  doc.close();

  // Small delay lets the iframe render before printing
  setTimeout(() => {
    iframe.contentWindow?.focus();
    iframe.contentWindow?.print();
    setTimeout(() => document.body.removeChild(iframe), 2000);
  }, 400);
}

// ─── Main card component ──────────────────────────────────────────────────────

interface BusinessReportProps {
  markdown: string;
  businessContext?: Record<string, any>;
}

export function BusinessReport({ markdown, businessContext }: BusinessReportProps) {
  const bodyRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);

  const title = businessContext?.business_type
    ? `${businessContext.business_type} — Business Plan`
    : 'Business Launch Report';

  const meta = [
    businessContext?.location && `📍 ${businessContext.location}`,
    businessContext?.budget   && `💰 ${businessContext.budget}`,
    '5 agents · MAYA Report',
    new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }),
  ].filter(Boolean).join(' · ');

  const handlePDF = () => {
    if (bodyRef.current) printReportAsPDF(bodyRef.current, title);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* ignore */ }
  };

  return (
    <div className="business-report-card">
      {/* Header */}
      <div className="report-header">
        <div className="report-header-left">
          <BarChart3 size={24} className="report-icon" style={{ color: '#f8fafc' }} />
          <div>
            <h3>{title}</h3>
            <p className="report-meta">{meta}</p>
          </div>
        </div>
        <div className="report-actions">
          <button onClick={handlePDF} className="btn-report-action" title="Save as PDF">
            <Download size={18} style={{ color: '#f8fafc' }} /> PDF
          </button>
          <button onClick={handleCopy} className="btn-report-action" title="Copy markdown">
            {copied ? <><Check size={18} className="text-primary" /> Copied</> : <><Copy size={18} style={{ color: '#f8fafc' }} /> Copy</>}
          </button>
        </div>
      </div>

      {/* Body — rendered markdown */}
      <div className="report-body" ref={bodyRef}>
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {markdown}
        </ReactMarkdown>
      </div>

      {/* Footer */}
      <div className="report-footer">
        <span className="report-badge">
          Generated by MAYA's Multi-Agent AI · 5 specialized agents analyzed your business
        </span>
      </div>
    </div>
  );
}
