/**
 * MAYA 1.0 - Global Type Definitions
 * Final Version for Multi-Agent Integration
 */

export interface Scheme {
  id: string | number;
  name: string;
  category: string;
  description: string;
  benefits: string[]; // NeonDB JSONB List
  
  // Database se aane waale core fields
  eligibility_criteria?: {
    type?: string;
    sector?: string;
    min_age?: number;
    [key: string]: any; // Allows flexible JSON keys from DB
  };
  required_documents?: string[]; // NeonDB JSONB List
  application_mode?: string;     // <--- Added this to fix Modal info
  link?: string;                 // Official URL column
  tags?: string[];
  
  // AI-Added Fields (Generated by Maya's Analyst Agent)
  relevance_score?: number; 
  explanation?: string;
  key_benefit?: string;
}

// 2. Chat Message Structure
export interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  type: 'text' | 'scheme-list'; // Identifies if the message has cards
  schemes?: Scheme[];           // Optional array for the grid
  agent?: string;               // Name of the agent (e.g., 'Scheme Navigator', 'Finance')
}

// 3. API Response from /api/chat/agent
export interface ChatResponse {
  response: string;
  agent: string;
  session_id: string;
  schemes: Scheme[]; // <--- Crucial fix for your TS error
}

// 4. Session & History Types
export interface UserSession {
  id: string;
  title: string;
  timestamp?: Date;
}

export interface HistoryMessage {
  id: number;
  role: 'user' | 'assistant';
  content: string;
  session_id: string;
  timestamp: string;
  schemes?: Scheme[]; // If your history service saves scheme results
}

// 5. User Profile (For Personalization)
export interface UserProfile {
  location?: string;
  industry?: string;
  business_stage?: 'idea' | 'startup' | 'scaling';
  social_category?: string;
}