export interface Scheme {
  id: string | number;
  name: string;
  category: string;
  description: string;
  benefits: string[];

  // Database core fields
  eligibility_criteria?: {
    type?: string;
    sector?: string;
    min_age?: number;
    [key: string]: any;
  };
  required_documents?: string[];
  application_mode?: string;
  link?: string;
  tags?: string[];

  // AI-Added Fields (Generated by Maya's Analyst Agent)
  relevance_score?: number;
  explanation?: string;
  key_benefit?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// V2: JSONB-based message content payloads
// These mirror the backend message_schemas.py models.
// ─────────────────────────────────────────────────────────────────────────────

export interface TextContent {
  text: string;
}

export interface SchemeResultsContent {
  query: string;
  summary: string;
  schemes: Scheme[];
}

export interface AgentResponseContent {
  agent: string;
  summary: string;
  sections: { title: string; body: string }[];
  sources: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Chat Message Structure (V2 — JSONB-aware)
// ─────────────────────────────────────────────────────────────────────────────

export interface Message {
  id: string;
  role: 'user' | 'assistant';
  /** V2: JSONB content. May be null during streaming (filling in live). */
  content: string | TextContent | SchemeResultsContent | AgentResponseContent;
  /** content_type mirrors the DB field */
  content_type?: 'text' | 'scheme_results' | 'agent_response' | 'business_report' | 'report_progress';
  timestamp: Date;
  /** Legacy UI type — kept for backwards compat with MessageComponent */
  type: 'text' | 'scheme-list';
  schemes?: Scheme[];
  agent?: string;
  /** True while the message is being streamed — shows cursor */
  isStreaming?: boolean;
  /** Business context extracted by the report pipeline */
  reportContext?: Record<string, any>;
}

// ─────────────────────────────────────────────────────────────────────────────
// API Response from /api/chat/agent
// ─────────────────────────────────────────────────────────────────────────────

export interface ChatResponse {
  response: string;
  agent: string;
  session_id: string;
  conversation_id?: string;  // V2
  schemes: Scheme[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Session & History Types
// ─────────────────────────────────────────────────────────────────────────────

export interface UserSession {
  id: string;
  title: string;
  timestamp?: Date;
}

/** V2: History message from /api/history/:conversation_id */
export interface HistoryMessage {
  id: string;
  role: 'user' | 'assistant';
  content_type: string;
  content: Record<string, any>;
  agent_used?: string;
  timestamp: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// User Profile (For Personalisation)
// ─────────────────────────────────────────────────────────────────────────────

export interface UserProfile {
  location?: string;
  industry?: string;
  business_stage?: 'idea' | 'startup' | 'scaling';
  social_category?: string;
}