"""Add onboarding profile fields

Revision ID: c6b0cfe195c2
Revises: 985f64df4cdb
Create Date: 2026-04-02 03:44:03.979993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b0cfe195c2'
down_revision: Union[str, Sequence[str], None] = '985f64df4cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversations', 'users', ['clerk_user_id'], ['clerk_user_id'])
    op.create_foreign_key(None, 'media_assets', 'users', ['clerk_user_id'], ['clerk_user_id'])
    op.drop_index(op.f('schemes_embedding_idx'), table_name='schemes', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('user_profiles', 'clerk_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user_profiles', ['clerk_user_id'])
    op.create_foreign_key(None, 'user_profiles', 'users', ['clerk_user_id'], ['clerk_user_id'])
    op.create_foreign_key(None, 'user_scheme_interactions', 'users', ['clerk_user_id'], ['clerk_user_id'])
    op.drop_constraint(op.f('users_clerk_user_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_clerk_user_id_key'), 'users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'user_scheme_interactions', type_='foreignkey')
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.alter_column('user_profiles', 'clerk_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('schemes_embedding_idx'), 'schemes', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint(None, 'media_assets', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
