"""
agents/draft_templates.py — Gemini prompt templates for scheme-specific project reports.

Each template produces a structured markdown document (not a plain cover letter).
The existing data/scheme_templates.py is still used for questions + document_checklist.
"""

DRAFT_PROMPT_TEMPLATES = {

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # PMEGP — Prime Minister Employment Generation Programme
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    "pmegp": {
        "display_name": "PMEGP Project Report",
        "subsidy_info": "15-35% subsidy on project cost up to ₹25 lakh (manufacturing) / ₹10 lakh (service)",
        "output_sections": [
            "Project At A Glance",
            "About the Promoter",
            "About the Project",
            "Market Potential",
            "Project Cost Breakdown",
            "Means of Finance",
            "Projected Revenue & Profitability",
            "Employment Generation",
            "Implementation Schedule",
            "Declaration",
        ],
        "prompt": """You are MAYA, generating a PMEGP Project Report for submission to KVIC/DIC.

## APPLICANT DETAILS (auto-filled from user profile):
- Name: {name}
- Category: {category} ({subsidy_rate}% subsidy applicable)
- Location: {city}, {state}
- Business Type: {business_type}
- Business Name: {business_name}
- Sector: {sector}
- Education: {education_level}
- Udyam Registered: {udyam_registered}

## ADDITIONAL CONTEXT PROVIDED BY APPLICANT:
{user_input}

## INSTRUCTIONS:
Generate a complete PMEGP Project Report in the following format.
Auto-fill all fields from the profile above. For fields not available,
use realistic estimates based on the business type and location, and mark
them with [TO BE UPDATED] so the user knows to verify.

---

# PMEGP PROJECT REPORT

## 1. PROJECT AT A GLANCE

| Parameter | Details |
|-----------|---------|
| Name of the Applicant | {name} |
| Category | {category} |
| Project Title | [Generate a concise title based on business_type] |
| Nature of Activity | {sector} |
| Location | {city}, {state} |
| Total Project Cost | ₹[estimate based on context] |
| Own Contribution | {own_contribution_pct}% = ₹[calculate] |
| PMEGP Subsidy ({subsidy_rate}%) | ₹[calculate] |
| Bank Loan | ₹[calculate remainder] |
| Employment Generated | [estimate] persons |

## 2. ABOUT THE PROMOTER

Write 100-150 words about the applicant's background, experience,
and motivation for starting this enterprise. Use profile data.

## 3. ABOUT THE PROJECT

Write 150-200 words about:
- What product/service will be offered
- How it addresses a market need in {city}
- Unique selling proposition

## 4. MARKET POTENTIAL

Write 150-200 words covering:
- Target customers in {city}, {state}
- Estimated market size
- Competition analysis
- Demand trends

## 5. PROJECT COST BREAKDOWN

Generate a realistic cost table:

| Component | Amount (₹) |
|-----------|------------|
| Land & Building | [estimate or "Rented - ₹X/month"] |
| Plant & Machinery | [estimate based on business_type] |
| Raw Material (3 months) | [estimate] |
| Working Capital | [estimate] |
| Pre-operative Expenses | [estimate] |
| **Total Project Cost** | **₹[total]** |

## 6. MEANS OF FINANCE

| Source | Percentage | Amount (₹) |
|--------|-----------|------------|
| Own Contribution | {own_contribution_pct}% | ₹[calculate] |
| PMEGP Subsidy | {subsidy_rate}% | ₹[calculate] |
| Bank Term Loan | [remainder]% | ₹[calculate] |
| **Total** | **100%** | **₹[total]** |

## 7. PROJECTED REVENUE & PROFITABILITY

| Year | Revenue (₹) | Expenses (₹) | Net Profit (₹) |
|------|-------------|--------------|----------------|
| Year 1 | [estimate] | [estimate] | [estimate] |
| Year 2 | [+20% growth] | [estimate] | [estimate] |
| Year 3 | [+20% growth] | [estimate] | [estimate] |

## 8. EMPLOYMENT GENERATION

| Type | Count |
|------|-------|
| Direct Employment | [estimate based on business] |
| Indirect Employment | [estimate] |
| Total | [sum] |
| Of which — Women | [estimate minimum 30%] |

## 9. IMPLEMENTATION SCHEDULE

| Activity | Timeline |
|----------|----------|
| Site Selection | Month 1 |
| Machinery Procurement | Month 1-2 |
| Installation & Trial Run | Month 2-3 |
| Raw Material Purchase | Month 3 |
| Commercial Production | Month 3-4 |

## 10. DECLARATION

I, {name}, hereby declare that the information provided above is true
to the best of my knowledge. I have not availed benefits under PMEGP
or any similar scheme of Government of India.

Place: {city}
Date: [TO BE FILLED]
Signature: _______________

---
*This project report was generated by MAYA — MSME MITRA.
All estimates should be verified with local market data before submission.
Fields marked [TO BE UPDATED] require the applicant's verification.*
""",
    },

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # MUDRA — Micro Units Development & Refinance Agency
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    "mudra": {
        "display_name": "Mudra Loan Application Brief",
        "subsidy_info": "Collateral-free loan: Shishu ≤₹50K | Kishore ≤₹5L | Tarun ≤₹10L",
        "output_sections": [
            "Mudra Category Determination",
            "Applicant Information",
            "Business Details",
            "Loan Requirement",
            "Repayment Plan",
            "Document Checklist",
        ],
        "prompt": """You are MAYA, generating a Mudra Loan Application Brief.

## APPLICANT DETAILS:
- Name: {name}
- Category: {category}
- Location: {city}, {state}
- Business: {business_type}
- Business Name: {business_name}
- Sector: {sector}
- Current Turnover: {turnover_range}
- Existing Loan: {existing_loan}

## APPLICANT'S REQUEST:
{user_input}

## DETERMINE MUDRA CATEGORY:
Based on the turnover and loan amount:
- Shishu: For loans up to ₹50,000
- Kishore: For loans ₹50,001 to ₹5,00,000
- Tarun: For loans ₹5,00,001 to ₹10,00,000

Generate a structured loan application brief:

---

# MUDRA LOAN APPLICATION BRIEF

## MUDRA CATEGORY: [Shishu/Kishore/Tarun — determine from user_input]

## 1. APPLICANT INFORMATION

| Field | Details |
|-------|---------|
| Full Name | {name} |
| Category | {category} |
| Business Name | {business_name} |
| Business Address | {city}, {state} |
| Nature of Business | {business_type} |
| Existing Bank Loans | {existing_loan} |

## 2. BUSINESS DETAILS

Write 100-150 words covering:
- Current business status (new/existing)
- Products/services offered
- Current monthly revenue estimate

## 3. LOAN REQUIREMENT

| Parameter | Details |
|-----------|---------|
| Loan Amount Requested | ₹[based on user_input or estimate] |
| Purpose of Loan | [based on user_input] |

### Purpose Breakdown:
| Use | Amount (₹) |
|-----|------------|
| [Working Capital / Machinery / Raw Material] | [amount] |
| **Total** | **₹[total]** |

## 4. REPAYMENT PLAN

| Parameter | Value |
|-----------|-------|
| Proposed Tenure | [3-5 years] |
| Expected Monthly Revenue | ₹[estimate] |
| Approx. Monthly EMI | ₹[calculate at ~10-12% interest] |
| EMI as % of Revenue | [should be <30%] |

## 5. REQUIRED DOCUMENTS CHECKLIST

- [ ] Identity Proof (Aadhaar Card)
- [ ] Address Proof
- [ ] PAN Card
- [ ] Passport-size Photographs (2)
- [ ] Business Registration / Udyam Certificate
- [ ] Bank Statements (last 6 months)
- [ ] Quotation for machinery/equipment (if applicable)
- [ ] Category Certificate (SC/ST/OBC — if applicable)
{additional_docs}

## 6. DECLARATION

I, {name}, confirm that the above information is true and correct.

Place: {city}
Date: [TO BE FILLED]

---
*Submit this brief along with required documents at your nearest bank branch.
All Mudra loans are collateral-free. Apply online at mudra.org.in*
""",
    },

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # STAND-UP INDIA
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    "standup_india": {
        "display_name": "Stand-Up India Application Brief",
        "subsidy_info": "₹10 Lakh to ₹1 Crore for SC/ST/Women entrepreneurs — greenfield enterprise",
        "output_sections": [
            "Eligibility Status",
            "Applicant Profile",
            "Enterprise Details",
            "Project Cost & Loan Computation",
            "Revenue Projection",
            "Repayment Schedule",
            "Document Checklist",
        ],
        "prompt": """You are MAYA, generating a Stand-Up India Loan Application Brief.

## APPLICANT DETAILS:
- Name: {name}
- Category: {category} (Must be SC/ST or Woman)
- Location: {city}, {state}
- Business: {business_type}
- Business Name: {business_name}
- Sector: {sector} (Must be manufacturing, services, or trading)
- Current Turnover: {turnover_range}

## APPLICANT'S REQUEST:
{user_input}

Generate a structured application:

---

# STAND-UP INDIA APPLICATION BRIEF

## ELIGIBILITY STATUS: [Determine based on category and sector]

| Criteria | Status |
|----------|--------|
| Category (SC/ST/Woman) | {category} — [Eligible/Check Required] |
| Enterprise Type | Greenfield — [Verify with applicant] |
| Sector | {sector} — [Eligible/Not Eligible] |
| Loan Range | ₹10L - ₹1Cr — [within range] |

## 1. APPLICANT PROFILE

| Field | Details |
|-------|---------|
| Full Name | {name} |
| Category | {category} |
| Address | {city}, {state} |
| Proposed Enterprise | {business_type} |
| Sector | {sector} |
| Udyam Registration | {udyam_registered} |

## 2. ENTERPRISE DETAILS

Write 150-200 words about the proposed enterprise:
- Nature of the greenfield enterprise
- Products/services
- Location and infrastructure needed
- Target market

## 3. PROJECT COST & LOAN COMPUTATION

| Component | Amount (₹) |
|-----------|------------|
| Land & Building | [estimate] |
| Plant & Machinery | [estimate] |
| Working Capital | [20-25% of total] |
| Other Fixed Assets | [estimate] |
| Pre-operative Expenses | [estimate] |
| **Total Project Cost** | **₹[total]** |

| Finance Source | Amount (₹) |
|---------------|------------|
| Applicant's Margin (10-25%) | ₹[calculate] |
| Stand-Up India Loan | ₹[calculate] |
| **Total** | **₹[total]** |

## 4. REVENUE PROJECTION

| Year | Revenue | Expenses | Net Profit |
|------|---------|----------|------------|
| Year 1 | ₹[est] | ₹[est] | ₹[est] |
| Year 2 | ₹[est] | ₹[est] | ₹[est] |
| Year 3 | ₹[est] | ₹[est] | ₹[est] |

## 5. REPAYMENT SCHEDULE

| Parameter | Details |
|-----------|---------|
| Loan Amount | ₹[amount] |
| Tenure | 7 years |
| Moratorium Period | Up to 18 months |
| Interest Rate | As per bank norms |
| Approx. Monthly EMI (post moratorium) | ₹[calculate] |

## 6. DOCUMENT CHECKLIST

- [ ] Identity Proof (Aadhaar + PAN)
- [ ] Category Certificate (SC/ST Caste Certificate / Gender proof)
- [ ] Address Proof (Aadhaar / Utility Bill)
- [ ] Passport-size Photographs (3)
- [ ] Detailed Project Report
- [ ] Quotations for Plant & Machinery
- [ ] Proof of Business Premises
- [ ] Bank Statements (last 12 months, if existing business)
- [ ] Udyam Registration Certificate

## APPLY ONLINE: standupmitra.in

---
*Stand-Up India loans are available at all Scheduled Commercial Bank branches.
Generated by MAYA — MSME MITRA*
""",
    },

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # ODOP — One District One Product (UP-specific)
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    "odop": {
        "display_name": "ODOP UP Application Brief",
        "subsidy_info": "Margin money subsidy 25% + interest subsidy up to 5% for district ODOP products",
        "output_sections": [
            "District-Product Mapping",
            "Applicant Information",
            "Enterprise Plan",
            "Financial Assistance",
            "Marketing Support",
            "Document Checklist",
        ],
        "prompt": """You are MAYA, generating an ODOP (One District One Product) Application.

## APPLICANT DETAILS:
- Name: {name}
- Category: {category}
- District: {city}, {state}
- Business: {business_type}
- Business Name: {business_name}
- Sector: {sector}
- Udyam Registered: {udyam_registered}

## APPLICANT'S REQUEST:
{user_input}

Generate the application:

---

# ODOP APPLICATION BRIEF
## One District One Product — Uttar Pradesh

## DISTRICT-PRODUCT MAPPING

| District | ODOP Product |
|----------|-------------|
| {city} | [Identify the known ODOP product for this UP district] |

**Applicant's Business:** {business_type}
**Alignment with ODOP:** [Assess alignment between the applicant's business and the district's ODOP product]

## 1. APPLICANT INFORMATION

| Field | Details |
|-------|---------|
| Name | {name} |
| Category | {category} |
| District | {city} |
| Business | {business_type} |
| Udyam Registered | {udyam_registered} |

## 2. ENTERPRISE PLAN

Write 150-200 words about:
- How the proposed business aligns with {city}'s ODOP product
- Production plan and capacity
- Supply chain and raw material sourcing
- Quality standards and certifications needed

## 3. FINANCIAL ASSISTANCE

| Component | Details |
|-----------|---------|
| Total Investment | ₹[estimate] |
| Margin Money Subsidy (25%) | ₹[calculate] |
| Interest Subsidy | Up to 5% on bank loan |
| Common Facility Centre | [if applicable] |

## 4. MARKETING SUPPORT

- ODOP product branding and packaging support
- Participation in trade fairs and exhibitions
- GeM (Government e-Marketplace) registration
- Amazon/Flipkart onboarding through ODOP program

## 5. DOCUMENT CHECKLIST

- [ ] Aadhaar Card
- [ ] PAN Card
- [ ] Udyam Registration
- [ ] Bank Account Details
- [ ] Business Plan / Project Brief
- [ ] Quotations for machinery/equipment
- [ ] Category Certificate (if applicable)
- [ ] Address/Domicile proof (UP resident)

## APPLY: odopup.in

---
*Generated by MAYA — MSME MITRA | ODOP UP Program*
""",
    },

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # PM VISHWAKARMA — Traditional artisans and craftspeople
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    "vishwakarma": {
        "display_name": "PM Vishwakarma Application Brief",
        "subsidy_info": "₹15,000 toolkit grant + ₹1-2L collateral-free loan at 5% interest + free skill training",
        "output_sections": [
            "Trade Eligibility",
            "Applicant Information",
            "Benefits Package",
            "Toolkit Requirement",
            "Training Plan",
            "Document Checklist",
        ],
        "prompt": """You are MAYA, generating a PM Vishwakarma Scheme Application Brief.

## APPLICANT DETAILS:
- Name: {name}
- Category: {category}
- Location: {city}, {state}
- Trade/Craft: {business_type}

## APPLICANT'S REQUEST:
{user_input}

## PM VISHWAKARMA ELIGIBLE TRADES (18 trades):
Carpenter, Blacksmith, Goldsmith, Potter, Sculptor, Cobbler, Mason,
Basket/Mat Maker, Doll & Toy Maker, Barber, Garland Maker, Washerman,
Tailor, Fishing Net Maker, Toolmaker, Locksmith, Boat Maker, Armourer.

---

# PM VISHWAKARMA APPLICATION BRIEF

## TRADE ELIGIBILITY

| Criteria | Details |
|----------|---------|
| Applicant's Trade | {business_type} |
| Eligible Under Vishwakarma | [Map to one of 18 trades — Eligible/Not Eligible] |
| Matched Trade Category | [Closest trade name from the 18] |
| Age Requirement (18+) | Assumed eligible |

## 1. APPLICANT INFORMATION

| Field | Details |
|-------|---------|
| Name | {name} |
| Trade | {business_type} |
| Location | {city}, {state} |
| Current monthly income | [estimate based on trade] |
| Family tradition in trade | [TO BE CONFIRMED by applicant] |

## 2. BENEFITS PACKAGE

### Phase 1 (Immediate):
| Benefit | Details |
|---------|---------|
| Recognition | PM Vishwakarma Certificate & ID Card |
| Toolkit Grant | ₹15,000 (for purchasing modern tools) |
| Skill Training | 5-15 days Basic Training + ₹500/day stipend |
| Collateral-free Loan | Up to ₹1,00,000 at 5% interest |

### Phase 2 (After training completion):
| Benefit | Details |
|---------|---------|
| Advanced Training | 15 days + ₹500/day stipend |
| Enhanced Loan | Up to ₹2,00,000 at 5% interest |
| Marketing Support | GeM onboarding + brand development |
| Digital Payment | QR code + digital transaction training |

## 3. TOOLKIT REQUIREMENT

Based on the trade ({business_type}), generate 5-8 specific modern tools with estimated costs totaling ~₹15,000:

| Tool | Estimated Cost (₹) |
|------|-------------------|
| [Tool 1 relevant to trade] | [cost] |
| [Tool 2 relevant to trade] | [cost] |
| [Tool 3 relevant to trade] | [cost] |
| [Tool 4 relevant to trade] | [cost] |
| [Tool 5 relevant to trade] | [cost] |
| **Total** | **~₹15,000** |

## 4. TRAINING PLAN

| Phase | Duration | Stipend | Focus |
|-------|----------|---------|-------|
| Basic | 5-15 days | ₹500/day | Modern techniques, quality standards |
| Advanced | 15 days | ₹500/day | Advanced skills, design, marketing |

## 5. DOCUMENT CHECKLIST

- [ ] Aadhaar Card (Aadhaar-linked mobile number mandatory)
- [ ] Aadhaar-linked Bank Account
- [ ] Passport-size Photograph
- [ ] Self-declaration of trade
- [ ] Family/Guru certification (Gram Panchayat/Ward level)

## REGISTRATION: pmvishwakarma.gov.in
**Step 1:** Visit nearest CSC Centre (Common Service Centre)
**Step 2:** Biometric verification with Aadhaar
**Step 3:** Trade verification by Gram Panchayat/Urban Body

---
*PM Vishwakarma registration is FREE at any CSC Centre. No middlemen or fees required.
Generated by MAYA — MSME MITRA*
""",
    },
}


# Map from data/scheme_templates.py keys to DRAFT_PROMPT_TEMPLATES keys
SCHEME_KEY_MAP: dict[str, str] = {
    "PMEGP": "pmegp",
    "Mudra": "mudra",
    "Stand-Up India": "standup_india",
    "ODOP": "odop",
    "Vishwakarma": "vishwakarma",
}


def get_pmegp_subsidy_rate(category: str, area: str = "urban") -> dict:
    """Calculate PMEGP subsidy rate based on applicant category and area."""
    rates = {
        ("General", "urban"): {"subsidy": 15, "own_contribution": 10},
        ("General", "rural"): {"subsidy": 25, "own_contribution": 10},
        ("SC", "urban"): {"subsidy": 25, "own_contribution": 5},
        ("SC", "rural"): {"subsidy": 35, "own_contribution": 5},
        ("ST", "urban"): {"subsidy": 25, "own_contribution": 5},
        ("ST", "rural"): {"subsidy": 35, "own_contribution": 5},
        ("OBC", "urban"): {"subsidy": 15, "own_contribution": 10},
        ("OBC", "rural"): {"subsidy": 25, "own_contribution": 10},
        ("Women", "urban"): {"subsidy": 25, "own_contribution": 5},
        ("Women", "rural"): {"subsidy": 35, "own_contribution": 5},
    }
    cat = category.strip()
    for key_cat in ["SC", "ST", "OBC", "Women"]:
        if key_cat.upper() in cat.upper():
            return rates.get((key_cat, area), rates[("General", area)])
    return rates.get(("General", area), {"subsidy": 15, "own_contribution": 10})
